<?php require_once("includes/header.php"); ?>
<script>
$(function(){
	$("#game_logo > a").fadeIn(0);
	
	var played = $.cookie('played');
	if(played === "true"){
		$(".entertowin").fadeOut(0);
	}
});
</script>

<h1>Double-Down Sweepstakes: Epic Reward Official Rules</h1>

<h2>NO PURCHASE NECESSARY.  A PURCHASE OR PAYMENT OF ANY KIND WILL NOT INCREASE YOUR CHANCES OF WINNING.</h2><br>
<ol class="rules">
	<!-- 1 -->
	<li><strong>Eligibility:</strong> Double-Down Sweepstakes: Epic Reward (the "Sweepstakes") is open only to legal residents of the fifty (50) United States and the District of Columbia who are at least eighteen (18) years old at the time of entry.  Employees of Virgin America, Inc., Mindspace, Inc., ePrize, Inc., and their parent and affiliate companies as well as the immediate family (spouse, parents, siblings and children) and household members of each such employee are not eligible.  The Sweepstakes is subject to all applicable federal, state, and local laws and regulations and is void where prohibited.  Participation constitutes entrant's full and unconditional agreement to these Official Rules and Sponsor's and Administrator's decisions, which are final and binding in all matters related to the Sweepstakes.  Winning the prize is contingent upon fulfilling all requirements set forth herein.</li>
	<!-- 2 -->
	<li><strong>Sponsor:</strong> Virgin America, Inc., 555 Airport Blvd., Burlingame, CA 94010. Administrator: ePrize, Inc., One ePrize Drive, Pleasant Ridge, MI 48069.</li>
	<!-- 3 -->
	<li><strong>Timing:</strong> The Sweepstakes begins on August 8, 2013 at 12:00 a.m. Eastern Time ("ET") and ends on September 6, 2013 at 11:59 p.m. ET (the "Promotion Period").  Mindspace, Inc.'s computer is the official time-keeping device for the Sweepstakes.</li>
	<!-- 4 -->
	<li><strong>How to Enter:</strong> There are two (2) ways to enter during the Promotion Period:
		
		<ol type="a">
		<li>Play Go Big Bingo: Visit http://gobigbingo.virginamerica.com and play Go Big Bingo by answering trivia questions to uncover spaces. Once you have achieved Bingo, follow the links and instructions to complete and submit the registration form including a valid email address, and click to enter the Epic Prize drawing. You automatically will receive one (1) entry into the Sweepstakes.  </li>
		<li>Enter Without Playing Go Big Bingo: Visit http://gobigbingo.virginamerica.com and follow the links and instructions to complete and submit the registration form including a valid email address, and click to enter the Epic Prize drawing. You automatically will receive one (1) entry into the Sweepstakes.</li>
		</ol>
		
		Limit: You may enter thirty (30) times during the Promotion Period. Maximum once per day.  Multiple entrants are not permitted to share the same email address.  Any attempt by any entrant to obtain more than the stated number of entries by using multiple/different email addresses, identities, registrations and logins, or any other methods will void that entrant's entries and that entrant may be disqualified.  Use of any automated system to participate is prohibited and will result in disqualification.  In the event of a dispute as to any registration, the authorized account holder of the email address used to register will be deemed to be the entrant.  The "authorized account holder" is the natural person assigned an email address by an Internet access provider, online service provider or other organization responsible for assigning email addresses for the domain associated with the submitted address.  The potential winner may be required to show proof of being the authorized account holder. 
	</li>
	<!-- 5 -->
	<li><strong>Grand Prize Drawing:</strong> Administrator is an independent judging organization whose decisions as to the administration and operation of the Sweepstakes and the selection of the potential winners are final and binding in all matters related to the Sweepstakes.  Administrator will randomly select the potential Sweepstakes winner from all eligible entries received during the Promotion Period, on or around September 16, 2013.  The potential winner will be notified by email or phone.  Except where prohibited, the potential Grand Prize winner (or parent/legal guardian if winner is a minor in his/her state of residence) will be required to sign and return a Declaration of Compliance, Liability and Publicity Release ("Declaration") which must be received by Administrator, within seven (7) days of the date notice or attempted notice is sent, in order to claim the prize.  If a potential winner cannot be contacted, fails to sign and return the Declaration or provide any other requested information, within the required time period, or the prize is returned as undeliverable, the potential winner forfeits the prize.  Receiving the prize is contingent upon compliance with these Official Rules.  In the event that the potential winner is disqualified for any reason, Sponsor will award the prize to an alternate winner by random drawing from among all remaining eligible entries.  Only three (3) alternate drawings will be held, after which the prize will remain un-awarded. Prize will be fulfilled approximately 8-10 weeks after the conclusion of the Sweepstakes.  </li>
	<!-- 6 -->
	<li><strong>Prize:</strong> ONE (1) GRAND PRIZE: 500,000 Elevate points. Elevate points are non-status qualifying.  Sponsor will deposit the points directly into winner's Elevate account. If winner does not have an Elevate account, he/she will need to create one in order to receive his/her prize. Elevate points are eligible for redemption on Virgin America or Virgin America's airline partners.  Terms and conditions of Elevate points apply. Approximate Retail Value: $10,000. 
Prize is non-transferable and no substitution will be made except as provided herein at the Sponsor's sole discretion. Sponsor reserves the right to substitute the prize for one of equal or greater value if the designated prize should become unavailable for any reason.  Winner is responsible for all taxes and fees associated with prize receipt and/or use.  Odds of winning the prize depend on the number of eligible entries received during the Promotion Period. </li>
	<!-- 7 -->
	<li><strong>Release:</strong> By receipt of the prize, winner agrees to release and hold harmless Sponsor, Mindspace, Inc., Administrator, and their respective subsidiaries, affiliates, suppliers, distributors, advertising/promotion agencies, and prize suppliers, and each of their respective parent companies and each such company's officers, directors, employees and agents (collectively, the "Released Parties") from and against any claim or cause of action, including, but not limited to, personal injury, death, or damage to or loss of property, arising out of participation in the Sweepstakes or receipt or use or misuse of any prize. </li>
	<!-- 8 -->
	<li><strong>Publicity:</strong> Except where prohibited, participation in the Sweepstakes constitutes winner's consent to Sponsor's and its agents' use of winner's name, likeness, photograph, voice, opinions and/or hometown and state for promotional purposes in any media, worldwide, without further payment or consideration. </li>
	<!-- 9 -->
	<li><strong>General Conditions:</strong> Sponsor reserves the right to cancel, suspend and/or modify the Sweepstakes, or any part of it, if any fraud, technical failures, human error or any other factor impairs the integrity or proper functioning of the Sweepstakes, as determined by Sponsor in its sole discretion.  In such event, Sponsor, in its sole discretion, may elect to hold a random drawing from among all eligible entries received up to the date of discontinuance for any or all of the prizes offered herein.  Sponsor reserves the right, in its sole discretion, to disqualify any individual it finds to be tampering with the entry process or the operation of the Sweepstakes or to be acting in violation of the Official Rules of this or any other promotion or in an unsportsmanlike or disruptive manner.  Any attempt by any person to deliberately undermine the legitimate operation of the Sweepstakes may be a violation of criminal and civil law, and, should such an attempt be made, Sponsor reserves the right to seek damages from any such person to the fullest extent permitted by law.  Sponsor's failure to enforce any term of these Official Rules shall not constitute a waiver of that provision. </li>
	<!-- 10 -->
	<li><strong>Limitations of Liability:</strong> The Released Parties are not responsible for: (1) any incorrect or inaccurate information, whether caused by entrants, printing errors or by any of the equipment or programming associated with or utilized in the Sweepstakes; (2) technical failures of any kind, including, but not limited to malfunctions, interruptions, or disconnections in phone lines or network hardware or software; (3) unauthorized human intervention in any part of the entry process or the Sweepstakes; (4) technical or human error which may occur in the administration of the Sweepstakes or the processing of entries; (5) late, lost, undeliverable, damaged or stolen mail; or (6) any injury or damage to persons or property which may be caused, directly or indirectly, in whole or in part, from entrant's participation in the Sweepstakes or receipt or use or misuse of any prize.  If for any reason an entrant's entry is confirmed to have been erroneously deleted, lost, or otherwise destroyed or corrupted, entrant's sole remedy is another entry in the Sweepstakes, if it is possible. No more than the stated number of prizes will be awarded.  In the event that production, technical, seeding, programming or any other reasons cause more than the stated number of prizes as set forth in these Official Rules to be available and/or claimed, Sponsor reserves the right to award only the stated number of prizes by a random drawing among all legitimate, un-awarded, eligible prize claims. </li>
	<!-- 11 -->
	<li><strong>Disputes:</strong> Except where prohibited, entrant agrees that: (1) any and all disputes, claims and causes of action arising out of or connected with this Sweepstakes or any prize awarded shall be resolved individually, without resort to any form of class action, and exclusively by the United States District Court for the Eastern District of Michigan (Southern Division) or the appropriate Michigan State Court located in Oakland County, Michigan; (2) any and all claims, judgments and awards shall be limited to actual out-of-pocket costs incurred, including costs associated with entering this Sweepstakes, but in no event attorneys' fees; and (3) under no circumstances will entrant be permitted to obtain awards for, and entrant hereby waives all rights to claim, indirect, punitive, incidental and consequential damages and any other damages, other than for actual out-of-pocket expenses, and any and all rights to have damages multiplied or otherwise increased.  All issues and questions concerning the construction, validity, interpretation and enforceability of these Official Rules, or the rights and obligations of the entrant and Sponsor in connection with the Sweepstakes, shall be governed by, and construed in accordance with, the laws of the State of Michigan without giving effect to any choice of law or conflict of law rules (whether of the State of Michigan or any other jurisdiction), which would cause the application of the laws of any jurisdiction other than the State of Michigan. </li>
	<!-- 12 -->
	<li><strong>Entrant's Personal Information:</strong> Information collected from entrants is subject to Administrator's Privacy Policy http://www.eprize.com/privacy-policy and Sponsor's Privacy Policy http://www.virginamerica.com/privacy-policy.html. </li>
	<!-- 13 -->
	<li><strong>Winner List:</strong> For a winner list, visit http://bit.ly/1cjVVwH. The winner list will be posted after winner confirmation is complete.</li>
</ol>
<br><br>
<p>&#169; 2013 ePrize, Inc. All rights reserved.</p>

<?php require_once("includes/footer.php"); ?>